//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectBOSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public long id { get; set; }
        public decimal accountid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public long age { get; set; }
        public double balance { get; set; }
    }
}
