//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectBOSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public long id { get; set; }
        public long service_id { get; set; }
        public long client_id { get; set; }
        public string by_date { get; set; }
        public double paid { get; set; }
        public long receiver { get; set; }
    }
}
